name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: us-east-1
      - name: Create lambda folder
        run: mkdir lambda
      - name: Install dependencies
        run: npm install
      - name: Zip File
        run: zip -r ./lambda/getSongs.zip *
      - name: Deploy to S3
        run: aws s3 sync ./lambda s3://lexsongslambda --delete
      - name: Deploy to lambda
        run: aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:724804006445:function:getSongs --zip-file fileb://lambda/getSongs.zip
